### ISSUE TITLE
Squeryl-record crash when field has ignoreField_? = true

### ISSUE THREAD

**Issue by brianhsu** [lift/framework#1297]
According to API documentation, when a Record field is declared as `ignoreField_? = true`, ORM should ignore it.

But the following code will lead to a exception thrown by squeryl-record.

```
object Bookstore extends Schema {
    val users = table[User]("users")
}

object User extends User with MetaRecord[User]
class User extends Record[User] with KeyedRecord[Long] {
    def meta = User

    @Column(name="id")
    val idField = new LongField(this, 1)
    val email = new EmailField(this, 255)
    val password = new PasswordField(this)
    val ignoreString = new StringField(this, "") {
        override def ignoreField_? = true
    }
}
```

Stack trace when create DDL from Squeryl.

```
scala> inTransaction { Bookstore.printDdl }
java.lang.RuntimeException: error while reflecting on metadata for (Some(private final net.liftweb.record.field.StringField org.bedone.model.User.ignoreString),Some(public net.liftweb.record.field.StringField org.bedone.model.User.ignoreString()),None,Set()) of class org.bedone.model.User
        at org.squeryl.internals.PosoMetaData$$anonfun$4.apply(PosoMetaData.scala:115)
        at org.squeryl.internals.PosoMetaData$$anonfun$4.apply(PosoMetaData.scala:80)
        at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:178)
        at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:347)
        at org.squeryl.internals.PosoMetaData.<init>(PosoMetaData.scala:80)
        at org.squeryl.View.<init>(View.scala:66)
        at org.squeryl.Table.<init>(Table.scala:29)
        at org.squeryl.Schema$class.table(Schema.scala:338)
        at org.bedone.model.Bookstore$.table(Test.scala:19)
        at org.bedone.model.Bookstore$.<init>(Test.scala:20)
        at org.bedone.model.Bookstore$.<clinit>(Test.scala)
        .............
Caused by: java.lang.RuntimeException: failed to find field ignoreString in Record metadata for class org.bedone.model.User
        at org.squeryl.internals.Utils$.throwError(Utils.scala:95)
        at net.liftweb.squerylrecord.RecordMetaDataFactory.fieldFrom$1(RecordMetaDataFactory.scala:41)
        at net.liftweb.squerylrecord.RecordMetaDataFactory.findMetaField(RecordMetaDataFactory.scala:45)
        at net.liftweb.squerylrecord.RecordMetaDataFactory.build(RecordMetaDataFactory.scala:70)
        at org.squeryl.internals.PosoMetaData$$anonfun$4.apply(PosoMetaData.scala:112)
        ... 49 more
```

**Comment by farmdawgnation** [comment]
This issue / PR is being closed because the Lift community has decided to decomission the Lift Persistence group of libraries including Mapper, Record, et al. We encourage folks to check out using some alternatives for their persistence needs. In particular the following libraries may be of interest:

* [ProtoQuill](https://github.com/zio/zio-protoquill)
* [slick](https://github.com/slick/slick)
* [scalasql](https://github.com/com-lihaoyi/scalasql)

There are likely others, as well! Please feel free to reach out on the Lift Mailing List if you have any questions or concerns.
